/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconTablerAdjustments: typeof import('~icons/tabler/adjustments.jsx')['default']
  const IconTablerChevronLeft: typeof import('~icons/tabler/chevron-left.jsx')['default']
  const IconTablerChevronRight: typeof import('~icons/tabler/chevron-right.jsx')['default']
  const IconTablerChevronsRight: typeof import('~icons/tabler/chevrons-right.jsx')['default']
  const IconTablerCircleOff: typeof import('~icons/tabler/circle-off.jsx')['default']
  const IconTablerContrastFilled: typeof import('~icons/tabler/contrast-filled.jsx')['default']
  const IconTablerCrop: typeof import('~icons/tabler/crop.jsx')['default']
  const IconTablerCrop11: (typeof import('~icons/tabler/crop11.tsx'))['default']
  const IconTablerCrop1_1: (typeof import('~icons/tabler/crop1_1.tsx'))['default']
  const IconTablerCropLandscape: typeof import('~icons/tabler/crop-landscape.jsx')['default']
  const IconTablerCropPortrait: typeof import('~icons/tabler/crop-portrait.jsx')['default']
  const IconTablerCrop_1_1: typeof import('~icons/tabler/crop-1-1.jsx')['default']
  const IconTablerCut: typeof import('~icons/tabler/cut.jsx')['default']
  const IconTablerDropletHalfFilled: typeof import('~icons/tabler/droplet-half-filled.jsx')['default']
  const IconTablerExchange: typeof import('~icons/tabler/exchange.jsx')['default']
  const IconTablerFilters: typeof import('~icons/tabler/filters.jsx')['default']
  const IconTablerGraph: typeof import('~icons/tabler/graph.jsx')['default']
  const IconTablerGraphFilled: typeof import('~icons/tabler/graph-filled.jsx')['default']
  const IconTablerPhoto: (typeof import('~icons/tabler/photo.tsx'))['default']
  const IconTablerPlayerPause: typeof import('~icons/tabler/player-pause.jsx')['default']
  const IconTablerPlayerPauseFilled: typeof import('~icons/tabler/player-pause-filled.jsx')['default']
  const IconTablerPlayerPlay: typeof import('~icons/tabler/player-play.jsx')['default']
  const IconTablerPlayerPlayFilled: typeof import('~icons/tabler/player-play-filled.jsx')['default']
  const IconTablerPlus: typeof import('~icons/tabler/plus.jsx')['default']
  const IconTablerRotateClockwise: typeof import('~icons/tabler/rotate-clockwise.jsx')['default']
  const IconTablerSettings: typeof import('~icons/tabler/settings.jsx')['default']
  const IconTablerSun: typeof import('~icons/tabler/sun.jsx')['default']
  const IconTablerTrash: typeof import('~icons/tabler/trash.jsx')['default']
  const IconTablerVideo: typeof import('~icons/tabler/video.jsx')['default']
  const IconTablerVideoPlus: typeof import('~icons/tabler/video-plus.jsx')['default']
  const IconTablerVolume: typeof import('~icons/tabler/volume.jsx')['default']
  const IconTablerVolumeOff: typeof import('~icons/tabler/volume-off.jsx')['default']
  const IconTablerVolume_3: typeof import('~icons/tabler/volume-3.jsx')['default']
  const IconTablerWand: typeof import('~icons/tabler/wand.jsx')['default']
}
