packages:
  - packages/*
  - docs

catalog:
  '@gltf-transform/cli': ^4.2.1
  '@gltf-transform/core': ^4.2.1
  '@gltf-transform/extensions': ^4.2.1
  '@gltf-transform/functions': ^4.2.1
  '@libav.js/variant-opus': ^6.8.8
  '@lokesh.dhakar/quantize': ^1.4.0
  '@types/base64-js': '^1.5.0'
  '@types/three': ^0.177.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vueuse/core': 13.4.0
  'base64-js': '^1.5.1'
  color-diff: ^1.4.0
  comlink: ^4.4.2
  filesize: ^10.1.6
  fine-jsx: ^0.0.11
  gl-matrix: ^3.4.4
  idb-keyval: ^6.2.2
  libavjs-webcodecs-polyfill: ^0.5.5
  mediabunny: '^1.34.4'
  stats.js: ^0.17.0
  three: ^0.177.0
  throttle-debounce: ^5.0.2
  twgl.js: ^6.2.0
  uid: ^2.0.2
  vue: ^3.5.26
  vue-i18n-lite: ^1.0.2
  yjs: ^13.6.27
  y-indexeddb: ^9.0.12
  yjs-orderedtree: 1.0.1-beta.3
  y-webrtc: ^10.3.0
  y-websocket: ^3.0.0
