packages:
  - packages/*
  - docs

catalog:
  '@gltf-transform/core': ^4.2.0
  '@gltf-transform/extensions': ^4.2.0
  '@gltf-transform/functions': ^4.2.0
  '@libav.js/variant-opus': ^6.7.7
  '@lokesh.dhakar/quantize': '^1.4.0'
  '@types/three': ^0.177.0
  buffer: ^6.0.3
  color-diff: '^1.4.0'
  comlink: '^4.4.2'
  ebml: ^3.0.0
  ebml-block: ^1.1.2
  filesize: ^10.1.6
  fine-jsx: ^0.0.11
  gl-matrix: ^3.4.3
  idb-keyval: '^6.2.2'
  libavjs-webcodecs-polyfill: ^0.5.3
  mp4-muxer: ^5.2.1
  mp4box: ^1.0.6
  stats.js: ^0.17.0
  three: ^0.177.0
  throttle-debounce: ^5.0.2
  twgl.js: ^6.1.1
  uid: ^2.0.2
  webm-muxer: ^5.1.3
