/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconTablerArrowBackUp: typeof import('~icons/tabler/arrow-back-up.jsx')['default']
  const IconTablerArrowForwardUp: typeof import('~icons/tabler/arrow-forward-up.jsx')['default']
  const IconTablerChevronLeft: typeof import('~icons/tabler/chevron-left.jsx')['default']
  const IconTablerChevronRight: typeof import('~icons/tabler/chevron-right.jsx')['default']
  const IconTablerChevronsRight: typeof import('~icons/tabler/chevrons-right.jsx')['default']
  const IconTablerCircleOff: typeof import('~icons/tabler/circle-off.jsx')['default']
  const IconTablerContrastFilled: typeof import('~icons/tabler/contrast-filled.jsx')['default']
  const IconTablerCrop: typeof import('~icons/tabler/crop.jsx')['default']
  const IconTablerCropLandscape: typeof import('~icons/tabler/crop-landscape.jsx')['default']
  const IconTablerCropPortrait: typeof import('~icons/tabler/crop-portrait.jsx')['default']
  const IconTablerCrop_1_1: typeof import('~icons/tabler/crop-1-1.jsx')['default']
  const IconTablerDropletHalfFilled: typeof import('~icons/tabler/droplet-half-filled.jsx')['default']
  const IconTablerFilters: typeof import('~icons/tabler/filters.jsx')['default']
  const IconTablerLoader2: typeof import('~icons/tabler/loader2.jsx')['default']
  const IconTablerPlayerPause: typeof import('~icons/tabler/player-pause.jsx')['default']
  const IconTablerPlayerPlay: typeof import('~icons/tabler/player-play.jsx')['default']
  const IconTablerPlus: typeof import('~icons/tabler/plus.jsx')['default']
  const IconTablerRotateClockwise: typeof import('~icons/tabler/rotate-clockwise.jsx')['default']
  const IconTablerSun: typeof import('~icons/tabler/sun.jsx')['default']
  const IconTablerVideo: typeof import('~icons/tabler/video.jsx')['default']
  const IconTablerWand: typeof import('~icons/tabler/wand.jsx')['default']
}
